from __future__ import annotations

import json
from pathlib import Path

from cv_pipeline_lab.core.graph import topological_sort
from cv_pipeline_lab.core.registry import BlockRegistry
from cv_pipeline_lab.core.serialization import pipeline_to_dict
from cv_pipeline_lab.core.types import PipelineModel


def export_python_script(pipeline: PipelineModel, registry: BlockRegistry) -> str:
    node_by_id = {n.id: n for n in pipeline.nodes}
    concept_nodes = [n for n in pipeline.nodes if registry.get_spec(n.block_type).is_concept]

    try:
        order = topological_sort(pipeline)
    except Exception:  # noqa: BLE001
        order = [n.id for n in pipeline.nodes]

    concept_comments: list[str] = []
    for node in concept_nodes:
        text = str(node.params.get("markdown", "")).strip()
        if text:
            concept_comments.append(f"# {node.title}: {text}")
        else:
            concept_comments.append(f"# {node.title}")

    per_node_comments: list[str] = []
    for node_id in order:
        node = node_by_id[node_id]
        spec = registry.get_spec(node.block_type)
        if spec.is_concept:
            continue
        per_node_comments.append(f"# - {node.title} ({node.block_type}) params={json.dumps(node.params, sort_keys=True)}")

    pipeline_json = json.dumps(pipeline_to_dict(pipeline), indent=2, sort_keys=True)

    script = f'''#!/usr/bin/env python3
"""Auto-generated by CV Pipeline Lab."""

import argparse
import json
import cv2
import matplotlib.pyplot as plt

from cv_pipeline_lab.core.executor import PipelineExecutor
from cv_pipeline_lab.core.registry import create_default_registry
from cv_pipeline_lab.core.serialization import pipeline_from_dict

PIPELINE_DICT = {pipeline_json}

# Concept notes
{chr(10).join(concept_comments) if concept_comments else '# (none)'}

# Compute nodes in execution order
{chr(10).join(per_node_comments) if per_node_comments else '# (none)'}


def _find_final_image(result):
    for node_id in reversed(result.order):
        node_res = result.node_results.get(node_id)
        if not node_res or node_res.error or node_res.skipped:
            continue
        img = node_res.outputs.get("image")
        if img is not None:
            return img, node_id
    return None, None


def main() -> None:
    parser = argparse.ArgumentParser(description="Run exported CV pipeline")
    parser.add_argument("--image", type=str, default=None, help="Override input image path")
    parser.add_argument("--save", type=str, default=None, help="Save final image to path")
    args = parser.parse_args()

    pipeline = pipeline_from_dict(PIPELINE_DICT)
    executor = PipelineExecutor(create_default_registry())
    result = executor.run(pipeline, image_override=args.image)

    if result.validation_errors:
        print("Validation errors:")
        for err in result.validation_errors:
            print(" -", err)
        raise SystemExit(1)

    print("Run logs:")
    for log in result.logs:
        print(log)

    final_img, final_node = _find_final_image(result)
    if final_img is None:
        print("No image output produced.")
        return

    print(f"Final image from node: {{final_node}}")
    if args.save:
        cv2.imwrite(args.save, final_img)
        print("Saved:", args.save)

    plt.figure(figsize=(10, 6))
    plt.imshow(cv2.cvtColor(final_img, cv2.COLOR_BGR2RGB))
    plt.title(f"Final output (node={{final_node}})")
    plt.axis("off")
    plt.tight_layout()
    plt.show()


if __name__ == "__main__":
    main()
'''
    return script


def write_python_export(path: str | Path, pipeline: PipelineModel, registry: BlockRegistry) -> None:
    p = Path(path).expanduser()
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(export_python_script(pipeline, registry))
